POST http://localhost:8080/payments
content-type: application/json

{
    "correlationId": "8b80fd56-70f1-45b6-8119-94f561c1e5d9",
    "amount": 19.90
}

GET http://localhost:8080/payments-summary

GET http://localhost:8080/payments-summary?from=2026-05-13T19:40:00Z&to=2026-05-13T19:46:59Z

# -------------------------------- payment processor
POST http://localhost:8001/payments
    content-type: application/json

    {
        "correlationId": "8a9b2c3d-e4f5-4a6b-8c7d-9e0f1a2b3c4d",
        "amount": 100.0,
        "requestedAt": "2026-04-29T22:32:00Z"
    }

GET http://localhost:8001/payments/service-health