quarkus.rest-client.payment-processor-default.url=${DEFAULT_API_URL}
quarkus.rest-client.payment-processor-fallback.url=${FALLBACK_API_URL}

# enable fault tolerance functionalities (retry, rate limit, etc.)
quarkus.fault-tolerance.enabled=true

quarkus.redis.hosts=${REDIS_HOST}